# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "58fb84d84ff9a463a0c5c1ce5a2ecd98b04454ec";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "58fb84d84ff9a463a0c5c1ce5a2ecd98b04454ec";
      fetchSubmodules = false;
      sha256 = "sha256-tIdYZwaipb8DbevxIXN2HVXVqHs79kVDwpnLZFCGbO4=";
    };
    date = "2025-02-26";
  };
  riscv-opcodes = {
    pname = "riscv-opcodes";
    version = "8899b32f218c85bf2559fa95f226bc2533316802";
    src = fetchFromGitHub {
      owner = "riscv";
      repo = "riscv-opcodes";
      rev = "8899b32f218c85bf2559fa95f226bc2533316802";
      fetchSubmodules = false;
      sha256 = "sha256-7CV/T8gnE7+ZPfYbn38Zx8fYUosTc8bt93wk5nmxu2c=";
    };
    date = "2025-02-14";
  };
  rvdecoderdb = {
    pname = "rvdecoderdb";
    version = "4572bb92fa458f27228ec0ad1aada2a9b7ea92d1";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "rvdecoderdb";
      rev = "4572bb92fa458f27228ec0ad1aada2a9b7ea92d1";
      fetchSubmodules = false;
      sha256 = "sha256-h6lUBQFeLfWY4cjyp/YImISUMcUvg15V/EJxc1RJoIQ=";
    };
    date = "2025-02-06";
  };
}
